stages:
  - build
  - commit
  - merge

variables:
  GIT_STRATEGY: fetch

export_pdf:
  stage: build
  image: alpine:latest
  before_script:
    - apk add --no-cache curl bash
  script:
    - echo "Exporting Google Doc..."
    - sh scripts/exportpdf.sh
  artifacts:
    paths:
      - hugo/static/files/louieladiona_resume.pdf
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'

commit_changes:
  stage: commit
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - sh scripts/commit_pdf.sh
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'

create_merge_request:
  stage: merge
  image: curlimages/curl:latest
  script:
    - |
      curl --request POST \
        --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        --data "source_branch=pdf-update" \
        --data "target_branch=main" \
        --data "title=Auto update resume PDF" \
        --data "remove_source_branch=true" \
        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" && $CI_PIPELINE_SOURCE == "push"'